// flow-typed signature: 07617b4209c1f3a0853f8aa5627029da
// flow-typed version: <<STUB>>/nighthawk_v^2.2.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nighthawk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nighthawk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nighthawk/dist/nighthawk' {
  declare module.exports: any;
}

declare module 'nighthawk/dist/nighthawk.min' {
  declare module.exports: any;
}

declare module 'nighthawk/lib/request' {
  declare module.exports: any;
}

declare module 'nighthawk/lib/response' {
  declare module.exports: any;
}

declare module 'nighthawk/lib/router' {
  declare module.exports: any;
}

declare module 'nighthawk/lib/supports-push-state' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nighthawk/dist/nighthawk.js' {
  declare module.exports: $Exports<'nighthawk/dist/nighthawk'>;
}
declare module 'nighthawk/dist/nighthawk.min.js' {
  declare module.exports: $Exports<'nighthawk/dist/nighthawk.min'>;
}
declare module 'nighthawk/index' {
  declare module.exports: $Exports<'nighthawk'>;
}
declare module 'nighthawk/index.js' {
  declare module.exports: $Exports<'nighthawk'>;
}
declare module 'nighthawk/lib/request.js' {
  declare module.exports: $Exports<'nighthawk/lib/request'>;
}
declare module 'nighthawk/lib/response.js' {
  declare module.exports: $Exports<'nighthawk/lib/response'>;
}
declare module 'nighthawk/lib/router.js' {
  declare module.exports: $Exports<'nighthawk/lib/router'>;
}
declare module 'nighthawk/lib/supports-push-state.js' {
  declare module.exports: $Exports<'nighthawk/lib/supports-push-state'>;
}
