// flow-typed signature: a8c6be5cc3a4f445bc8e0a6d80a4a6af
// flow-typed version: <<STUB>>/push.js_v^1.0.5/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'push.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'push.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'push.js/bin/push' {
  declare module.exports: any;
}

declare module 'push.js/bin/push.min' {
  declare module.exports: any;
}

declare module 'push.js/bin/serviceWorker' {
  declare module.exports: any;
}

declare module 'push.js/bin/serviceWorker.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'push.js/bin/push.js' {
  declare module.exports: $Exports<'push.js/bin/push'>;
}
declare module 'push.js/bin/push.min.js' {
  declare module.exports: $Exports<'push.js/bin/push.min'>;
}
declare module 'push.js/bin/serviceWorker.js' {
  declare module.exports: $Exports<'push.js/bin/serviceWorker'>;
}
declare module 'push.js/bin/serviceWorker.min.js' {
  declare module.exports: $Exports<'push.js/bin/serviceWorker.min'>;
}
